// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304114713_RenameAdjustementsToAdjustment")]
    partial class RenameAdjustementsToAdjustment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Domain.Models.Brokers.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("BrokerStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CommissionPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerCode")
                        .IsUnique();

                    b.ToTable("Brokers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            BrokerCode = "BRK-001",
                            BrokerStatus = 0,
                            CommissionPercentage = 10.00m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "broker@insurance.local",
                            Name = "Default Broker",
                            PhoneNumber = "0700000000"
                        });
                });

            modelBuilder.Entity("Domain.Models.Buildings.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildingType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConstructionYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsuredValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiskIndicatiors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SurfaceArea")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Domain.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CountyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Bucharest"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            CountyId = new Guid("22222222-2222-2222-2222-222222222223"),
                            Name = "Cluj-Napoca"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            CountyId = new Guid("22222222-2222-2222-2222-222222222223"),
                            Name = "Florești"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333336"),
                            CountyId = new Guid("22222222-2222-2222-2222-222222222224"),
                            Name = "Timișoara"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333337"),
                            CountyId = new Guid("22222222-2222-2222-2222-222222222224"),
                            Name = "Lugoj"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333338"),
                            CountyId = new Guid("22222222-2222-2222-2222-222222222225"),
                            Name = "Iași"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333339"),
                            CountyId = new Guid("22222222-2222-2222-2222-222222222226"),
                            Name = "Brașov"
                        });
                });

            modelBuilder.Entity("Domain.Models.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Domain.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Romania"
                        });
                });

            modelBuilder.Entity("Domain.Models.County", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Bucharest"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Cluj"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Timiș"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Iași"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            CountryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Brașov"
                        });
                });

            modelBuilder.Entity("Domain.Models.Geography.Address.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Domain.Models.Metadatas.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeRateToBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Code = "RON",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExchangeRateToBase = 1m,
                            IsActive = true,
                            Name = "Romanian Leu"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Code = "EUR",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExchangeRateToBase = 4.95m,
                            IsActive = true,
                            Name = "Euro"
                        });
                });

            modelBuilder.Entity("Domain.Models.Metadatas.FeeConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeeType", "EffectiveFrom");

                    b.ToTable("FeeConfigurations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveFrom = "2026-01-01",
                            FeeType = 0,
                            IsActive = true,
                            Name = "Default broker commission",
                            Percentage = 0.10m
                        });
                });

            modelBuilder.Entity("Domain.Models.Metadatas.RiskFactorConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdjustementPercentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BuildingType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceID")
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RiskLevel", "BuildingType");

                    b.HasIndex("RiskLevel", "ReferenceID");

                    b.ToTable("RiskFactorConfigurations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AdjustementPercentage = 0.05m,
                            IsActive = true,
                            Name = "City risk factor",
                            ReferenceID = new Guid("33333333-3333-3333-3333-333333333333"),
                            RiskLevel = 2
                        });
                });

            modelBuilder.Entity("Domain.Models.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PolicyStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PolicyVersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Domain.Models.Policies.PolicyAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PolicyVersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolicyVersionId", "AdjustmentType");

                    b.ToTable("PolicyAdjustments");
                });

            modelBuilder.Entity("Domain.Models.Policies.PolicyEndorsement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EndorsementType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewVersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OldVersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyEndorsements");
                });

            modelBuilder.Entity("Domain.Models.Policies.PolicyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActiveVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyVersions");
                });

            modelBuilder.Entity("Domain.Models.Buildings.Building", b =>
                {
                    b.HasOne("Domain.Models.Geography.Address.Address", "Address")
                        .WithOne("Building")
                        .HasForeignKey("Domain.Models.Buildings.Building", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.City", null)
                        .WithMany("Buildings")
                        .HasForeignKey("CityId");

                    b.HasOne("Domain.Models.Clients.Client", "Client")
                        .WithMany("Buildings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Models.City", b =>
                {
                    b.HasOne("Domain.Models.County", "County")
                        .WithMany("Cities")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("Domain.Models.County", b =>
                {
                    b.HasOne("Domain.Models.Country", "Country")
                        .WithMany("Counties")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Models.Geography.Address.Address", b =>
                {
                    b.HasOne("Domain.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Clients.Client", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Models.Policies.Policy", b =>
                {
                    b.HasOne("Domain.Models.Brokers.Broker", "Broker")
                        .WithMany("Policies")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Buildings.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Metadatas.Currency", null)
                        .WithMany("Policies")
                        .HasForeignKey("CurrencyId");

                    b.Navigation("Broker");

                    b.Navigation("Building");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Models.Policies.PolicyAdjustment", b =>
                {
                    b.HasOne("Domain.Models.Policies.PolicyVersion", "PolicyVersion")
                        .WithMany("PolicyAdjustments")
                        .HasForeignKey("PolicyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyVersion");
                });

            modelBuilder.Entity("Domain.Models.Policies.PolicyEndorsement", b =>
                {
                    b.HasOne("Domain.Models.Policies.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Domain.Models.Policies.PolicyVersion", b =>
                {
                    b.HasOne("Domain.Models.Metadatas.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Policies.Policy", "Policy")
                        .WithMany("PolicyVersions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Domain.Models.Brokers.Broker", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Domain.Models.City", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Domain.Models.Clients.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Domain.Models.Country", b =>
                {
                    b.Navigation("Counties");
                });

            modelBuilder.Entity("Domain.Models.County", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Models.Geography.Address.Address", b =>
                {
                    b.Navigation("Building");
                });

            modelBuilder.Entity("Domain.Models.Metadatas.Currency", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Domain.Models.Policies.Policy", b =>
                {
                    b.Navigation("PolicyVersions");
                });

            modelBuilder.Entity("Domain.Models.Policies.PolicyVersion", b =>
                {
                    b.Navigation("PolicyAdjustments");
                });
#pragma warning restore 612, 618
        }
    }
}
